#
# SHARP configuration
#

obj-$(CONFIG_SHARP_SHLOG) += shrlog/

obj-$(CONFIG_SHARP_SHTIMER) += shtimer/

obj-$(CONFIG_SHARP_BOOT) += shboot/

obj-$(CONFIG_SHARP_PNP) += pnp/

obj-$(CONFIG_SHARP_SHDIAG_SMD) += shdiag/
